### ISSUE TITLE
SocketClient.kt Bug Report

### ISSUE THREAD

**Issue by simon0302010** [Megonno/RaspiCar#11]
Here are some potential bugs and issues in the provided code:

1. The `connect` function is marked as `suspend`, but it does not actually suspend the coroutine. It performs blocking I/O operations in the `withContext(Dispatchers.IO)` block, which could lead to thread starvation and poor performance.

To fix this issue, you can use `kotlinx.coroutines` built-in functions for asynchronous I/O operations, such as `kotlinx.coroutines.channels` for receiving messages and `kotlinx.coroutines.selects` for handling timeouts and exceptions.

2. The `connect` function catches `ConnectException` and sets the `client`, `bufferedReader`, and `printWriter` variables to `null`. However, it does not clear the `clientJob` variable, which could lead to a memory leak if the client is not able to connect to the server.

To fix this issue, you can add a check for `clientJob` before launching a new coroutine and cancel and clear the previous job if it exists.

3. The `sendMessage` function does not check if the `printWriter` variable is `null` before performing I/O operations. This could lead to a `NullPointerException` if the client is not connected to the server.

To fix this issue, you can add a null check before performing I/O operations and print a message if the `printWriter` variable is `null`.

4. The `stop` function cancels the `clientJob` and waits for it to complete, but it does not close the `client`, `bufferedReader`, and `printWriter` variables if the job is cancelled.

To fix this issue, you can add a check for `clientJob` completion cause and close the resources if the job is cancelled.

Here is an updated version of the code with the suggested fixes:

```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.channels.ReceiveChannel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.selects.select
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.PrintWriter
import java.net.ConnectException
import java.net.Socket

class SocketClient {
    private val clientScope = CoroutineScope(Dispatchers.IO)
    private var client: Socket? = null
    private var bufferedReader: BufferedReader? = null
    private var printWriter: PrintWriter? = null
    private var clientJob: Job? = null
    private val messageChannel = Channel<String>()

    suspend fun connect(hostname: String, port: Int, inputHandler: (String) -> Unit) {
        try {
            client = Socket(hostname, port)
            println("Connected with ${client!!.remoteSocketAddress}")

            bufferedReader = BufferedReader(InputStreamReader(client!!.inputStream))
            printWriter = PrintWriter(client!!.outputStream)
            println("Init input and output")

            clientJob = clientScope.launch {
                while (true) {
                    select<Unit> {
                        client!!.inputStream.available().takeIf { it > 0 }?.let {
                            onReceive(it)
                        }
                        onTimeout()
                    }
                }
            }

            launch {
                for (message in messageChannel) {
                    inputHandler.invoke(message)
                }
            }
        } catch (exception: ConnectException) {
            println("Exception: ${exception.message}")

            client = null
            bufferedReader = null
            printWriter = null
            clientJob?.cancel()
            clientJob = null

            return
        }
    }

    private suspend fun onReceive(bufferSize: Int) {
        val buffer = ByteArray(bufferSize)
        client!!.inputStream.read(buffer)
        val message = String(buffer).trimEnd()

        if (message.isNotBlank()) {
            println("Received: $message")

            messageChannel.send(message)
        }
    }

    private suspend fun onTimeout() {
        delay(1000)

        if (client?.isClosed == true) {
            println("Disconnected")

            client = null
            bufferedReader = null
            printWriter = null
            clientJob?.cancel()
            clientJob = null
        }
    }

    fun sendMessage(message: String) {
        printWriter?.print(message)
        printWriter?.flush()
        if (printWriter != null) println("Sent: $message") else println("Output channel is null")
    }

    suspend fun stop() {
        clientJob?.cancel()
        clientJob?.join()

        if (clientJob?.completionExceptionOrNull() != null) {
            bufferedReader?.close()
            printWriter?.close()
            client?.close()
            println("Disconnected")

            bufferedReader = null
            printWriter = null
            client = null
            clientJob = null
        }
    }
}
```

Note that this updated version of the code is just a suggestion and may not cover all edge cases and error handling scenarios. It is recommended to thoroughly test and debug the code before using it in production.

**Comment by Megonno** [comment]
This file has changed
