### ISSUE TITLE
Platform.kt Bug Report

### ISSUE THREAD

**Issue by simon0302010** [Megonno/RaspiCar#2]
Based on the provided code, I can't see any obvious bugs. However, there are some potential improvements that could be made:

1. The `getPlatform` function is not annotated with `@JvmStatic`, which means if you want to call this function from Java or use it as a top-level function in a Kotlin/JS or Kotlin/Native environment, you will need to create an instance of the `WasmPlatform` class or use an object expression. Adding `@JvmStatic` will make the function a static method in the generated Java class, allowing it to be called without creating an instance.

Here's the updated code with the suggested improvement:

```kotlin
import kotlin.jvm.JvmStatic

class WasmPlatform {
    val name: String = "Web with Kotlin/Wasm"
}

@JvmStatic
fun getPlatform() = WasmPlatform()
```

2. Another potential improvement is to make the `name` property immutable by using `val` instead of `var`. This way, you ensure that the name cannot be changed after the object is created.

Here's the updated code with the suggested improvement:

```kotlin
import kotlin.jvm.JvmStatic

class WasmPlatform {
    val name: String = "Web with Kotlin/Wasm"
}

@JvmStatic
fun getPlatform() = WasmPlatform()
```

**Comment by Megonno** [comment]
This file no longer exists
