### ISSUE TITLE
RaspiCar.kt Bug Report

### ISSUE THREAD

**Issue by simon0302010** [Megonno/RaspiCar#3]
Here are some potential issues with the given code:

1. The `SocketClient()` constructor call in the `main()` function is not accompanied by any parameter values, but the `SocketClient` class may require parameters for its constructor.
2. The `connect()` function of the `SocketClient` class is called with `host` and `port` parameters, but the code inside the curly braces `{}` is empty. This may cause the connection to not be established properly.
3. The `while (true)` loop in the `main()` function may cause the program to become unresponsive or consume too many resources, as it will continuously send messages to the server without any pauses or conditions to break out of the loop.
4. The `readln()` function is used to read input from the console, but there is no error handling in case the user fails to provide any input. This may cause the program to crash or become unresponsive.
5. The code does not handle any exceptions or errors that may occur during the execution of the `connect()` or `sendMessage()` functions. This may cause the program to crash or become unresponsive without providing any useful error messages.

To fix these issues, you may consider adding error handling, implementing a proper loop condition, and providing default values for the `SocketClient` constructor. Additionally, you may want to consider adding comments or documentation to explain the code's functionality and requirements.

**Comment by Megonno** [comment]
Your AI is misunderstanding something
